### ISSUE TITLE
NameError: name 'joint_heatmap_3d' is not defined

### ISSUE THREAD

**Issue by tacalvin** [chhankyao/visdb#3]
Thank you for releasing your code. 
I have tried to run your code and believe there is a typo here. 
https://github.com/chhankyao/visdb/blob/4070812c1a96ecc454a208f5b60d8fd42f772caa/common/nets/module.py#L69-L70

Is this supposed to be `joint_heatmap` instead of `joint_heatmap_3d`?

**Comment by chhankyao** [comment]
You're right. It should be joint_heatmap. Thanks for the correction!
